### ISSUE TITLE
Disconnecting from network

### ISSUE THREAD

**Issue by janipewter** [ssDhp/bt-Pico#16]
Can this handle disconnecting from phone network if it goes out of cellular coverage? Will it automatically reconnect when it comes back into signal?

**Comment by ssDhp** [comment]
I have modified the code in the latest commit. Now if connection to the cellular network breaks for any reason (including going out of cellular coverage) the device will reset itself and attempt to reconnect. 
The implementation is not the best. I will try to rewrite it in the future.
